spring.application.name=shop-validator

server.port=8081
spring.jpa.hibernate.ddl-auto=none

spring.kafka.bootstrap-servers=172.17.183.49:9092

# Define o deserializador "inteligente" que sabe lidar com erros
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Diz para o ErrorHandlingDeserializer que o deserializador real é o JsonDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# E não esqueça a correção do pacote confiável:
spring.kafka.consumer.properties.spring.json.trusted.packages=*