### Buscar shop
GET http://localhost:8080/shop
Accept: application/json

> src/main/resources/responses/shop.json

### Criar shop
POST http://localhost:8080/shop
Content-Type: application/json

{
  "items": [
    {
      "productIdentifier": "1234567",
      "amount": 100,
      "price": 1000
    },
    {
      "productIdentifier": "1234567",
      "amount": 100,
      "price": 1000
    }
  ]
}

> src/main/resources/responses/shop-create.json
